export const SERVICE_URLSV2 = {
  // service URL's version 2 Dot Net Backend (API End-Points)
  GeneralLookup: 'generallookup/getgenerallookups',
  ClearCahce: 'permissions/clearusersessioncache',
  GetPatientByEmail: 'patientportal/getpatientbyemail',
  GetPatientDetailsById: 'patientportal/getpatientdetailsbyid',
  GetPatientEncounterDetails: 'patientportal/getpatientencounterdetails', //Also used for Dashboard  Widget TimelineWidget
  DownloadDocument: 'ccda/download',
  GetPatientCCDAActivityLog: 'patientportal/getpatientccdaactivitylog',
  InsertActivityLog: 'patientportal/insertactivitylog',
  CreateAuthorizedUser: 'patientuser/authorizepatientuserrequest',
  Share: '/ccda/share',
  GetPatientAuthorizedUser: 'patientportal/getpatientauthorizeduser',
  UpdatePatientAuthorizedUserAccess: 'patientportal/updatepatientauthorizeduseraccess',
  GetPatientUserRequestByCode: 'patientuser/getpatientuserrequestbycode',
  GenerateOtp: 'patientuser/generateotp',
  AddPatientUser: 'patientuser/addpatientuser',
  GetToken: 'patientuser/gettoken',
  GetSharingModulesData : 'patientportal/getsharingmodulesdata',
  UpdateSharingModulesData : 'patientportal/updatesharingmodulesdata',
  GetServerTime:'dashboard/getservertime',
  saveConsentForm: 'patientportal/SubmitConsentForm',
  GetConsentFormData: 'patientportal/GetConsentFormData',
  GetConsentFormContent: 'patientportal/getcontent',
  GetPatientActiveMedications: 'patientportal/GetCurrentMedicationsWidget',
  GetPatientAllergies : 'patientportal/GetAllergiesWidget',
  getpatientvitals : 'patientportal/GetMyVitalsWidget',
  getpatientproblems : 'patientportal/GetMyHealthConditionsWidget',
  getpatientappointments : 'patientportal/GetUpcomingAppointmentsWidget',
  getunsignedlabordertestbypatientid : 'patientportal/GetLabResultsWidget',
  getdashboardconfigurations : 'patientportal/getdashboardconfigurations',
  saveDashboardConfiguration : 'patientportal/savedashboardwidgetconfigurations',
  getAllDocumentTypes : 'patientportal/getalldocumenttype',
  getAllSelectedDocuments : 'patientportal/getallunsigneddocument',
  getPatientDocumentInfo : 'patientportal/getpatientdocument',
  getDownloadPatientDocument : 'patientportal/downloadpatientdocument'
};