export const SERVICE_URLSV2 = {
  // service URL's version 2 Dot Net Backend (API End-Points related to Patient Portal)
  GeneralLookup: 'generallookup/getgenerallookups',
  ClearCahce: 'permissions/clearusersessioncache',
  GetServerTime:'dashboard/getservertime',
  CreateAuthorizedUser: 'patientuser/authorizepatientuserrequest',
  GetPatientUserRequestByCode: 'patientuser/getpatientuserrequestbycode',
  GenerateOtp: 'patientuser/generateotp',
  AddPatientUser: 'patientuser/addpatientuser',
  GetToken: 'patientuser/gettoken',
  DownloadDocument: 'ccda/download',
  Share: '/ccda/share',
  GetPatientByEmail: 'patientportal/getpatientbyemail',
  GetPatientDetailsById: 'patientportal/getpatientdetailsbyid',
  GetPatientEncounterDetails: 'patientportal/getpatientencounterdetails', //Also used for Dashboard  Widget TimelineWidget
  GetPatientCCDAActivityLog: 'patientportal/getpatientccdaactivitylog',
  InsertActivityLog: 'patientportal/insertactivitylog',
  GetPatientAuthorizedUser: 'patientportal/getpatientauthorizeduser',
  UpdatePatientAuthorizedUserAccess: 'patientportal/updatepatientauthorizeduseraccess',
  GetSharingModulesData : 'patientportal/getsharingmodulesdata',
  UpdateSharingModulesData : 'patientportal/updatesharingmodulesdata',
  SaveConsentForm: 'patientportal/SubmitConsentForm',
  GetConsentFormData: 'patientportal/GetConsentFormData',
  GetConsentFormContent: 'patientportal/getcontent',
  GetPatientActiveMedications: 'patientportal/GetCurrentMedicationsWidget',
  GetPatientAllergies : 'patientportal/GetAllergiesWidget',
  GetPatientVitals : 'patientportal/GetMyVitalsWidget',
  GetPatientProblems : 'patientportal/GetMyHealthConditionsWidget',
  GetPatientAppointments : 'patientportal/GetUpcomingAppointmentsWidget',
  GetUnsignedLaborderTestByPatientId : 'patientportal/GetLabResultsWidget',
  GetDashboardConfigurations : 'patientportal/getdashboardconfigurations',
  SaveDashboardConfiguration : 'patientportal/savedashboardwidgetconfigurations',
  getAllDocumentTypes : 'patientportal/getalldocumenttype',
  getAllSelectedDocuments : 'patientportal/getallunsigneddocument',
  getPatientDocumentInfo : 'patientportal/getpatientdocument',
  getDownloadPatientDocument : 'patientportal/downloadpatientdocument',
  generateResetPasswordOtp : 'patientportal/generateresetpasswordotp',
  resetPatientPassword : 'patientportal/resetpatientpassword'
};