export const documentTypes: Record<string, any> = [
  {
      "id": 6,
      "parentId": null,
      "patientId": null,
      "name": "Consent Forms",
      "docTypeCount": 1,
      "status": true,
      "documentSubTypes": [
          {
              "id": 22,
              "parentId": 6,
              "patientId": null,
              "name": "Research Consent Forms",
              "docTypeCount": 0,
              "status": true,
              "documentSubTypes": null,
              "createdBy": null,
              "updatedBy": null,
              "createdAt": null,
              "updatedAt": null,
              "isDeleted": null,
              "totalRows": 0,
              "totalCount": 0
          },
          {
              "id": 21,
              "parentId": 6,
              "patientId": null,
              "name": "Treatment Consent Forms",
              "docTypeCount": 1,
              "status": true,
              "documentSubTypes": null,
              "createdBy": null,
              "updatedBy": null,
              "createdAt": null,
              "updatedAt": null,
              "isDeleted": null,
              "totalRows": 0,
              "totalCount": 0
          }
      ],
      "createdBy": null,
      "updatedBy": null,
      "createdAt": null,
      "updatedAt": null,
      "isDeleted": null,
      "totalRows": 0,
      "totalCount": 0
  },
  {
      "id": 1,
      "parentId": null,
      "patientId": null,
      "name": "Lab Result",
      "docTypeCount": 0,
      "status": true,
      "documentSubTypes": [
          {
              "id": 9,
              "parentId": 1,
              "patientId": null,
              "name": "Albumin Creatinine",
              "docTypeCount": 0,
              "status": true,
              "documentSubTypes": null,
              "createdBy": null,
              "updatedBy": null,
              "createdAt": null,
              "updatedAt": null,
              "isDeleted": null,
              "totalRows": 0,
              "totalCount": 0
          },
          {
              "id": 8,
              "parentId": 1,
              "patientId": null,
              "name": "Comprehensive Metabolic Panel",
              "docTypeCount": 0,
              "status": true,
              "documentSubTypes": null,
              "createdBy": null,
              "updatedBy": null,
              "createdAt": null,
              "updatedAt": null,
              "isDeleted": null,
              "totalRows": 0,
              "totalCount": 0
          },
          {
              "id": 7,
              "parentId": 1,
              "patientId": null,
              "name": "Lab (CBC)",
              "docTypeCount": 0,
              "status": true,
              "documentSubTypes": null,
              "createdBy": null,
              "updatedBy": null,
              "createdAt": null,
              "updatedAt": null,
              "isDeleted": null,
              "totalRows": 0,
              "totalCount": 0
          }
      ],
      "createdBy": null,
      "updatedBy": null,
      "createdAt": null,
      "updatedAt": null,
      "isDeleted": null,
      "totalRows": 0,
      "totalCount": 0
  },
  {
      "id": 4,
      "parentId": null,
      "patientId": null,
      "name": "Orders",
      "docTypeCount": 3,
      "status": true,
      "documentSubTypes": [
          {
              "id": 15,
              "parentId": 4,
              "patientId": null,
              "name": "Prescriptions",
              "docTypeCount": 2,
              "status": true,
              "documentSubTypes": null,
              "createdBy": null,
              "updatedBy": null,
              "createdAt": null,
              "updatedAt": null,
              "isDeleted": null,
              "totalRows": 0,
              "totalCount": 0
          },
          {
              "id": 17,
              "parentId": 4,
              "patientId": null,
              "name": "Procedure Orders",
              "docTypeCount": 1,
              "status": true,
              "documentSubTypes": null,
              "createdBy": null,
              "updatedBy": null,
              "createdAt": null,
              "updatedAt": null,
              "isDeleted": null,
              "totalRows": 0,
              "totalCount": 0
          },
          {
              "id": 16,
              "parentId": 4,
              "patientId": null,
              "name": "Test Orders",
              "docTypeCount": 0,
              "status": true,
              "documentSubTypes": null,
              "createdBy": null,
              "updatedBy": null,
              "createdAt": null,
              "updatedAt": null,
              "isDeleted": null,
              "totalRows": 0,
              "totalCount": 0
          }
      ],
      "createdBy": null,
      "updatedBy": null,
      "createdAt": null,
      "updatedAt": null,
      "isDeleted": null,
      "totalRows": 0,
      "totalCount": 0
  },
  {
      "id": 3,
      "parentId": null,
      "patientId": null,
      "name": "Patient Records",
      "docTypeCount": 0,
      "status": true,
      "documentSubTypes": [
          {
              "id": 14,
              "parentId": 3,
              "patientId": null,
              "name": "Discharge Summaries",
              "docTypeCount": 0,
              "status": true,
              "documentSubTypes": null,
              "createdBy": null,
              "updatedBy": null,
              "createdAt": null,
              "updatedAt": null,
              "isDeleted": null,
              "totalRows": 0,
              "totalCount": 0
          },
          {
              "id": 12,
              "parentId": 3,
              "patientId": null,
              "name": "History And Physical (H&P)",
              "docTypeCount": 0,
              "status": true,
              "documentSubTypes": null,
              "createdBy": null,
              "updatedBy": null,
              "createdAt": null,
              "updatedAt": null,
              "isDeleted": null,
              "totalRows": 0,
              "totalCount": 0
          },
          {
              "id": 13,
              "parentId": 3,
              "patientId": null,
              "name": "Progress Notes",
              "docTypeCount": 0,
              "status": true,
              "documentSubTypes": null,
              "createdBy": null,
              "updatedBy": null,
              "createdAt": null,
              "updatedAt": null,
              "isDeleted": null,
              "totalRows": 0,
              "totalCount": 0
          }
      ],
      "createdBy": null,
      "updatedBy": null,
      "createdAt": null,
      "updatedAt": null,
      "isDeleted": null,
      "totalRows": 0,
      "totalCount": 0
  },
  {
      "id": 26,
      "parentId": null,
      "patientId": null,
      "name": "Patient Referrals",
      "docTypeCount": 0,
      "status": true,
      "documentSubTypes": [
          {
              "id": 27,
              "parentId": 26,
              "patientId": null,
              "name": "Incoming Referral",
              "docTypeCount": 0,
              "status": true,
              "documentSubTypes": null,
              "createdBy": null,
              "updatedBy": null,
              "createdAt": null,
              "updatedAt": null,
              "isDeleted": null,
              "totalRows": 0,
              "totalCount": 0
          }
      ],
      "createdBy": null,
      "updatedBy": null,
      "createdAt": null,
      "updatedAt": null,
      "isDeleted": null,
      "totalRows": 0,
      "totalCount": 0
  },
  {
      "id": 2,
      "parentId": null,
      "patientId": null,
      "name": "Practice Documents",
      "docTypeCount": 1,
      "status": true,
      "documentSubTypes": [
          {
              "id": 10,
              "parentId": 2,
              "patientId": null,
              "name": "Agreements",
              "docTypeCount": 1,
              "status": true,
              "documentSubTypes": null,
              "createdBy": null,
              "updatedBy": null,
              "createdAt": null,
              "updatedAt": null,
              "isDeleted": null,
              "totalRows": 0,
              "totalCount": 0
          },
          {
              "id": 11,
              "parentId": 2,
              "patientId": null,
              "name": "Staff Signoffs",
              "docTypeCount": 0,
              "status": true,
              "documentSubTypes": null,
              "createdBy": null,
              "updatedBy": null,
              "createdAt": null,
              "updatedAt": null,
              "isDeleted": null,
              "totalRows": 0,
              "totalCount": 0
          }
      ],
      "createdBy": null,
      "updatedBy": null,
      "createdAt": null,
      "updatedAt": null,
      "isDeleted": null,
      "totalRows": 0,
      "totalCount": 0
  },
  {
      "id": 23,
      "parentId": null,
      "patientId": null,
      "name": "Prior Auth",
      "docTypeCount": 0,
      "status": true,
      "documentSubTypes": [
          {
              "id": 24,
              "parentId": 23,
              "patientId": null,
              "name": "PA - Medication",
              "docTypeCount": 0,
              "status": true,
              "documentSubTypes": null,
              "createdBy": null,
              "updatedBy": null,
              "createdAt": null,
              "updatedAt": null,
              "isDeleted": null,
              "totalRows": 0,
              "totalCount": 0
          },
          {
              "id": 25,
              "parentId": 23,
              "patientId": null,
              "name": "PA - Procedure/Test",
              "docTypeCount": 0,
              "status": true,
              "documentSubTypes": null,
              "createdBy": null,
              "updatedBy": null,
              "createdAt": null,
              "updatedAt": null,
              "isDeleted": null,
              "totalRows": 0,
              "totalCount": 0
          }
      ],
      "createdBy": null,
      "updatedBy": null,
      "createdAt": null,
      "updatedAt": null,
      "isDeleted": null,
      "totalRows": 0,
      "totalCount": 0
  },
  {
      "id": 5,
      "parentId": null,
      "patientId": null,
      "name": "Reports",
      "docTypeCount": 0,
      "status": true,
      "documentSubTypes": [
          {
              "id": 35,
              "parentId": 5,
              "patientId": null,
              "name": "Diagnostic Data",
              "docTypeCount": 0,
              "status": true,
              "documentSubTypes": null,
              "createdBy": null,
              "updatedBy": null,
              "createdAt": null,
              "updatedAt": null,
              "isDeleted": null,
              "totalRows": 0,
              "totalCount": 0
          },
          {
              "id": 18,
              "parentId": 5,
              "patientId": null,
              "name": "Laboratory Reports",
              "docTypeCount": 0,
              "status": true,
              "documentSubTypes": null,
              "createdBy": null,
              "updatedBy": null,
              "createdAt": null,
              "updatedAt": null,
              "isDeleted": null,
              "totalRows": 0,
              "totalCount": 0
          },
          {
              "id": 19,
              "parentId": 5,
              "patientId": null,
              "name": "Pathology Reports",
              "docTypeCount": 0,
              "status": true,
              "documentSubTypes": null,
              "createdBy": null,
              "updatedBy": null,
              "createdAt": null,
              "updatedAt": null,
              "isDeleted": null,
              "totalRows": 0,
              "totalCount": 0
          },
          {
              "id": 20,
              "parentId": 5,
              "patientId": null,
              "name": "Radiology Reports",
              "docTypeCount": 0,
              "status": true,
              "documentSubTypes": null,
              "createdBy": null,
              "updatedBy": null,
              "createdAt": null,
              "updatedAt": null,
              "isDeleted": null,
              "totalRows": 0,
              "totalCount": 0
          }
      ],
      "createdBy": null,
      "updatedBy": null,
      "createdAt": null,
      "updatedAt": null,
      "isDeleted": null,
      "totalRows": 0,
      "totalCount": 0
  }
];